// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yuqujmglvhnkgqflnlys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1cXVqbWdsdmhua2dxZmxubHlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NDM2NDEsImV4cCI6MjA3MDAxOTY0MX0.iUf91RvvjpUFHMSC1TX0sXpRxnD5LE7IvKH41ZncdGk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});